"""new migrate

Revision ID: 078d1b3bb5de
Revises: 909128777511
Create Date: 2024-07-12 11:39:07.792227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078d1b3bb5de'
down_revision = '909128777511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gambar_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gambar_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
