"""Migration

Revision ID: 909128777511
Revises: 
Create Date: 2024-07-11 19:36:30.830551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909128777511'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gambar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tumor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=16), nullable=False),
    sa.Column('perawatan', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nomor_telepon', sa.String(length=20), nullable=False),
    sa.Column('gambar_id', sa.Integer(), nullable=False),
    sa.Column('tempat_lahir', sa.Text(), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('kata_sandi', sa.Text(), nullable=False),
    sa.Column('tipe', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['gambar_id'], ['gambar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nomor_telepon')
    )
    op.create_table('riwayat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap_pasien', sa.String(length=80), nullable=False),
    sa.Column('hasil', sa.String(length=30), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('gambar_id', sa.Integer(), nullable=False),
    sa.Column('tumor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gambar_id'], ['gambar.id'], ),
    sa.ForeignKeyConstraint(['tumor_id'], ['tumor.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riwayat')
    op.drop_table('user')
    op.drop_table('tumor')
    op.drop_table('gambar')
    # ### end Alembic commands ###
